import { createError } from 'h3'
import { serverSupabaseClient, serverSupabaseUser } from '#supabase/server'

export default defineEventHandler(async (event) => {
    try {
        const client = await serverSupabaseClient(event)
        const user = await serverSupabaseUser(event)

        // Check if user is authenticated
        if (!user) {
            throw createError({
                statusCode: 401,
                statusMessage: 'Not authenticated'
            })
        }

        // Check if current user is an admin
        const { data: adminRecord } = await client
            .from('admin')
            .select('email')
            .eq('email', user.email)
            .single()

        if (!adminRecord) {
            throw createError({
                statusCode: 403,
                statusMessage: 'Unauthorized - Admin access required'
            })
        }

        // Get the emails from request body
        const body = await readBody(event)
        const { emails } = body

        if (!emails || !Array.isArray(emails) || emails.length === 0) {
            throw createError({
                statusCode: 400,
                statusMessage: 'Invalid request - emails array required'
            })
        }

        // Check if any of the emails already exist in the admin table
        const { data: existingAdmins } = await client
            .from('admin')
            .select('email')
            .in('email', emails)

        const existingEmails = existingAdmins?.map(a => a.email) || []
        const newEmails = emails.filter(email => !existingEmails.includes(email))

        if (newEmails.length === 0) {
            return {
                success: true,
                message: 'All emails already exist as admins',
                added: 0,
                skipped: existingEmails.length,
                skippedEmails: existingEmails
            }
        }

        // Prepare records to insert (id and created_at will be auto-generated by Supabase)
        const recordsToInsert = newEmails.map(email => ({
            email: email,
            name: email.split('@')[0] // Default name from email prefix
        }))

        // Insert new admin records
        const { data, error } = await client
            .from('admin')
            .insert(recordsToInsert)
            .select()

        if (error) {
            console.error('Error inserting admins:', error)
            throw createError({
                statusCode: 500,
                statusMessage: error.message || 'Failed to add admin users'
            })
        }

        return {
            success: true,
            message: `Successfully added ${newEmails.length} admin user(s)`,
            added: newEmails.length,
            skipped: existingEmails.length,
            skippedEmails: existingEmails,
            data: data
        }

    } catch (err) {
        console.error('Add admin error:', err)

        // If it's already a createError, rethrow it
        if (err.statusCode) {
            throw err
        }

        // Otherwise wrap it
        throw createError({
            statusCode: 500,
            statusMessage: err?.message || 'Internal server error'
        })
    }
})
